# Generated by Django 4.2.1 on 2023-05-14 11:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("applications", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="job",
            options={"verbose_name": "Job", "verbose_name_plural": "Jobs"},
        ),
        migrations.AlterModelOptions(
            name="jobheader",
            options={
                "verbose_name": "Job header",
                "verbose_name_plural": "Job headers",
            },
        ),
    ]
